site_name: erudito
repo_url: https://github.com/adriacabeza/erudito

theme:
  name: "material"
  logo: logo.jpeg
  features:
    - content.code.copy
    -

plugins:
  - mkdocstrings
  - search

watch:
  - src

nav:
  - Home: 'index.md'
  - User Guide: 'setup.md'
  - Documentation:
      - 'ingest.md'
      - 'query.md'
      - 'faiss_wrapper.md'
      - 'reader.md'
  - 'utils.md'
  - Special Thanks: 'special_thanks.md'


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
